rootProject.name = "Transformers"
include(":sample")
include(":core")
include(":types")
include(":transformers:glide")
include(":transformers:glide-gpu")
include(":transformers:picasso")
include(":transformers:picasso-gpu")
include(":transformers:fresco")
include(":transformers:fresco-gpu")
include(":transformers:coil")
include(":transformers:coil-gpu")
