rootProject.name = "Image Transformations"
include(":sample")
include(":core")
include(":types")
include(":transformations:glide")
include(":transformations:glide-gpu")
include(":transformations:picasso")
include(":transformations:picasso-gpu")
include(":transformations:fresco")
include(":transformations:coil")
include(":transformations:coil-gpu")
